enum CommonConstants {
    API_RESPONSE_SUCCESSFUL = 200,
    API_RESPONSE_ACCEPTED = 202,
    API_RESPONSE_UNAUTHORIZED_ACCESS = 401,
    API_RESPONSE_CONFLICTS_IN_REQUEST = 409,
    API_RESPONSE_UNPROCESSABLE_ENTITY = 422,
}

export { CommonConstants };